### ISSUE TITLE
Unable to disable NFS3 using USE_NFS3=OFF

### ISSUE THREAD

**Issue by chaserhkj** [nfs-ganesha/nfs-ganesha#1416]
Related: #1011 

Tested on nixpkgs build with v14.1 release:

```console
nix build --no-link -vL --impure --expr '(builtins.getFlake "nixpkgs").legacyPackages.x86_64-linux.nfs-ganesha.overrideAttrs (old: {cmakeFlags = old.cmakeFlags ++ ["-DUSE_NFS3=OFF"];})'
```

Full build logs:  [nix-build.log](https://github.com/user-attachments/files/31321064/nix-build.log)

Relevant error sections:
```console
nfs-ganesha> /build/source/src/support/server_stats.c: In function 'grpc_get_v3_full_stats':
nfs-ganesha> /build/source/src/support/server_stats.c:4376:35: error: 'nfs_core_parameter_t' {aka 'struct nfs_core_param'} has no member named 'enable_FULLV3STATS'; did you mean 'enable_FULLV4STATS'?
nfs-ganesha>  4376 |         if (!nfs_param.core_param.enable_FULLV3STATS) {
nfs-ganesha>       |                                   ^~~~~~~~~~~~~~~~~~
nfs-ganesha>       |                                   enable_FULLV4STATS
nfs-ganesha> [ 44%] Building C object Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_layoutreturn.c.o
nfs-ganesha> /build/source/src/support/server_stats.c:4381:60: error: 'nfsproc3_to_str' undeclared (first use in this function); did you mean 'nfsop4_to_str'?
nfs-ganesha>  4381 |         fill_grpc_full_stats(stats_out, NFS_V3_NB_COMMAND, nfsproc3_to_str,
nfs-ganesha>       |                                                            ^~~~~~~~~~~~~~~
nfs-ganesha>       |                                                            nfsop4_to_str
nfs-ganesha> /build/source/src/support/server_stats.c:4381:60: note: each undeclared identifier is reported only once for each function it appears in
nfs-ganesha> /build/source/src/support/server_stats.c:4382:30: error: 'v3_full_stats' undeclared (first use in this function); did you mean 'v4_full_stats'?
nfs-ganesha>  4382 |                              v3_full_stats, true);
nfs-ganesha>       |                              ^~~~~~~~~~~~~
nfs-ganesha>       |                              v4_full_stats
nfs-ganesha> [ 45%] Building C object Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_link.c.o
nfs-ganesha> cc1: warning: command-line option '-Wno-redundant-move' is valid for C++/ObjC++ but not for C
nfs-ganesha> /build/source/src/support/server_stats.c:4384:21: error: 'v3_full_stats_time' undeclared (first use in this function); did you mean 'v4_full_stats_time'?
nfs-ganesha>  4384 |         *time_out = v3_full_stats_time;
nfs-ganesha>       |                     ^~~~~~~~~~~~~~~~~~
nfs-ganesha>       |                     v4_full_stats_time
nfs-ganesha> cc1: warning: command-line option '-Wno-redundant-move' is valid for C++/ObjC++ but not for C
nfs-ganesha> make[2]: *** [support/CMakeFiles/support.dir/build.make:233: support/CMakeFiles/support.dir/server_stats.c.o] Error 1
nfs-ganesha> make[2]: *** Waiting for unfinished jobs....
```

[nixpkgs reference packaging of nfs-ganesha](https://github.com/NixOS/nixpkgs/blob/ffb3c9b700e759be2ef13237c9d8f953b32a1e46/pkgs/by-name/nf/nfs-ganesha/package.nix#L70)

**Comment by chaserhkj** [comment]
Ok this is fixed with 21c88a5

Just not in V14.1. nix build needs to bump version or backport this patch.
