### ISSUE TITLE
Failed to compile v6.2

### ISSUE THREAD

**Issue by derekbit** [nfs-ganesha/nfs-ganesha#1200]
Hello experts, any solution to the issue?

```
...

15.06 [ 34%] Building C object SAL/CMakeFiles/sal.dir/recovery/recovery_fs_ng.c.o
15.22 [ 34%] Building C object SAL/CMakeFiles/sal.dir/recovery/recovery_longhorn.c.o
15.50 [ 34%] Built target sal
15.52 [ 35%] Building C object RPCAL/CMakeFiles/rpcal.dir/connection_manager.c.o
15.60 /nfs-ganesha/src/RPCAL/connection_manager.c:169:2: error: initializer element is not constant
15.60   callback_default;
15.60   ^~~~~~~~~~~~~~~~
15.61 make[2]: *** [RPCAL/CMakeFiles/rpcal.dir/build.make:79: RPCAL/CMakeFiles/rpcal.dir/connection_manager.c.o] Error 1
15.61 make[1]: *** [CMakeFiles/Makefile2:1490: RPCAL/CMakeFiles/rpcal.dir/all] Error 2
15.61 make: *** [Makefile:156: all] Error 2
------
```

**Comment by dang** [comment]
I haven't seen that.  All the relevant elements are static or static const, so it *should* be okay?

**Comment by derekbit** [comment]
We didn't see the issue when compiling v5.x codes by the steps https://github.com/longhorn/longhorn-share-manager/blob/master/package/Dockerfile#L8-L43, but ran into the issue in v6.1 and v6.2.

Anything wrong?

**Comment by ffilz** [comment]
Yea, I'm not sure why that initializer is causing a problem. And it compiles for me. Maybe a compiler version issue?

**Comment by derekbit** [comment]
> Yea, I'm not sure why that initializer is causing a problem. And it compiles for me. Maybe a compiler version issue?

Thank you. Let me try a newer compiler version.
What's your compiler version?

**Comment by derekbit** [comment]
The issue is gone after upgrading the gcc to v14. Thank you.

BTW, failed to compile it when set `-DUSE_NFS3=OFF`. The complier complains unable to find `nfsproc3_to_str` if `-DUSE_NFS3` is `OFF`. 
https://github.com/nfs-ganesha/nfs-ganesha/blob/V6.2/src/MainNFSD/nfs_metrics.c#L309

**Comment by sachinpunadikar** [comment]
Analyzing

**Comment by sachinpunadikar** [comment]
Fixed this issue by 
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1204553
Waiting for review & merge

**Comment by ffilz** [comment]
patch merged, closing.
