### ISSUE TITLE
version 2.7.6 does not build on debian unstable with ceph 12.2

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#449]
/usr/bin/cc -g -O2 -fdebug-prefix-map=/build/nfs-ganesha-2.7.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DCHECK_FUNCTION_EXISTS=ceph_ll_fallocate  -Wl,-z,relro -Wl,-z,now  -rdynamic CMakeFiles/cmTC_f418c.dir/CheckFunctionExists.c.o  -o cmTC_f418c -lcephfs 
/usr/bin/ld: CMakeFiles/cmTC_f418c.dir/CheckFunctionExists.c.o: in function `main':
/usr/share/cmake-3.13/Modules/CheckFunctionExists.c:17: undefined reference to `ceph_ll_fallocate'

/usr/bin/cc -g -O2 -fdebug-prefix-map=/build/nfs-ganesha-2.7.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DCHECK_FUNCTION_EXISTS=ceph_start_reclaim  -Wl,-z,relro -Wl,-z,now  -rdynamic CMakeFiles/cmTC_8275c.dir/CheckFunctionExists.c.o  -o cmTC_8275c -lcephfs 
/usr/bin/ld: CMakeFiles/cmTC_8275c.dir/CheckFunctionExists.c.o: in function `main':
/usr/share/cmake-3.13/Modules/CheckFunctionExists.c:17: undefined reference to `ceph_start_reclaim'

I wonder why version 2.7.4 built without a problem.

Any hints?

**Comment by dang** [comment]
Something is messed up with your cmake.  src/cmake/modules/FindCEPHFS.cmake checks the libraries on your system to see if ceph_ll_fallocate() and ceph_start_reclaim() are available, and only builds them if they are.  Could you have run cmake with a different version of ceph installed, and then downgraded it?

**Comment by christmart** [comment]
The error happens in the cmake config step

**Comment by christmart** [comment]
The problem was the wrong build dependency on gluster-common instead of now libglusterfs-dev for the Debian build. Because of the missing libglusterfs-dev libraries apparently some of the following tests failed and stopped the build process.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
