### ISSUE TITLE
Build failure with maintainer build on v7.0 (server_channel_dir may be used uninitialized)

### ISSUE THREAD

**Issue by dsg22** [nfs-ganesha/nfs-ganesha#1320]
Building with -DCMAKE_BUILD_TYPE=Maintainer fails due to error:

```
/build/source/src/Protocols/NFS/nfs4_op_bind_conn.c: In function 'nfs4_op_bind_conn':
/build/source/src/Protocols/NFS/nfs4_op_bind_conn.c:226:48: error: 'server_channel_dir' may be used uninitialized [-Werror=maybe-uninitialized]
  226 |         resok_BIND_CONN_TO_SESSION4->bctsr_dir = server_channel_dir;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/build/source/src/Protocols/NFS/nfs4_op_bind_conn.c:126:34: note: 'server_channel_dir' was declared here
  126 |         channel_dir_from_server4 server_channel_dir;
      |                                  ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/build.make:121: Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_bind_conn.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by ffilz** [comment]
Hmm, looks like this is a new strict compile time check...

This case can't actually happen, but it could be fixed with a default case in the preceding switch statement that handles an unexpected value.
